
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ybsymjhhqyuciewpiulk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlic3ltamhocXl1Y2lld3BpdWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTY2MjMsImV4cCI6MjA2MjI5MjYyM30.3Yo_s7vcKZ92ak78fCyvBXlqZHuOZ3hwDM4Y37_Ipc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
